import type { Metadata } from "next";
import { IBM_Plex_Sans, Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import ParallaxProviderWrapper from "@/providers/parallax-provider-wrapper";

import Template from "@/components/animations/template";
import PageFadeIn from "@/components/animations/page-fade-in";

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSans.variable} ${inter.variable} relative antialiased`}
      >
        <PageFadeIn>
          <Header />
          <Template>
            <ParallaxProviderWrapper>{children}</ParallaxProviderWrapper>
          </Template>
        </PageFadeIn>
      </body>
    </html>
  );
}
